spring:
 datasource:
  url: jdbc:sqlserver://X.X.X.X:1433;databaseName=appconfig
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  username: XXXX
  password: XXXX 
  
 jpa:
  #hibernate:
   #ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.SQLServer2012Dialect