spring:
 datasource:
  url: jdbc:mysql://localhost:3306/jpasample
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: password 

 
 jpa:
  #hibernate:
   #ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect